# Generated by Django 5.0.7 on 2025-08-14 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratechange',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='ratechange',
            name='rental',
        ),
        migrations.RemoveField(
            model_name='ratechange',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='historicalrental',
            name='contract_code',
            field=models.CharField(blank=True, help_text='Общий номер договора для всей группы (root)', max_length=64),
        ),
        migrations.AddField(
            model_name='historicalrental',
            name='parent',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rental.rental'),
        ),
        migrations.AddField(
            model_name='historicalrental',
            name='root',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rental.rental'),
        ),
        migrations.AddField(
            model_name='historicalrental',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='rental',
            name='contract_code',
            field=models.CharField(blank=True, help_text='Общий номер договора для всей группы (root)', max_length=64),
        ),
        migrations.AddField(
            model_name='rental',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='rental.rental'),
        ),
        migrations.AddField(
            model_name='rental',
            name='root',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group', to='rental.rental'),
        ),
        migrations.AddField(
            model_name='rental',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='HistoricalRateChange',
        ),
        migrations.DeleteModel(
            name='RateChange',
        ),
    ]
