# Generated by Django 5.0.7 on 2025-08-14 20:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_ratechange_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['root', 'status'], name='idx_rental_root_status'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['root'], name='idx_rental_root'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['status'], name='idx_rental_status'),
        ),
        migrations.AddConstraint(
            model_name='rental',
            constraint=models.UniqueConstraint(fields=('root', 'version'), name='uq_rental_root_version'),
        ),
    ]
