# Generated by Django 5.0.7 on 2025-08-14 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_rental_idx_rental_root_status_rental_idx_rental_root_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rentalbatteryassignment',
            index=models.Index(fields=['battery', 'start_at'], name='idx_assign_batt_start'),
        ),
    ]
