# Generated by Django 5.0.7 on 2025-08-14 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_set_root_version_contract_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrental',
            name='battery_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество арендованных батарей'),
        ),
        migrations.AddField(
            model_name='historicalrental',
            name='battery_numbers',
            field=models.TextField(blank=True, help_text='Номера арендованных батарей'),
        ),
        migrations.AddField(
            model_name='rental',
            name='battery_count',
            field=models.PositiveIntegerField(default=0, help_text='Количество арендованных батарей'),
        ),
        migrations.AddField(
            model_name='rental',
            name='battery_numbers',
            field=models.TextField(blank=True, help_text='Номера арендованных батарей'),
        ),
    ]
