# Generated by Django 5.0.7 on 2025-08-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_historicalrental_battery_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrental',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='historicalrental',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rental',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='rental',
            name='updated_by_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
