# Generated by Django 5.0.7 on 2025-09-24 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0008_backfill_names'),
    ]

    operations = [
        migrations.AddField(
            model_name='battery',
            name='status',
            field=models.CharField(blank=True, choices=[('rented', 'rented'), ('service', 'service'), ('sold', 'sold'), ('available', 'available')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='historicalbattery',
            name='status',
            field=models.CharField(blank=True, choices=[('rented', 'rented'), ('service', 'service'), ('sold', 'sold'), ('available', 'available')], max_length=16, null=True),
        ),
    ]
