# Generated by Django 5.0.7 on 2025-09-24 21:07
from django.db import migrations
from decimal import Decimal

CODES = [
"V3/100","V3/101","V3/102","V3/103","V3/104","V3/105","V3/106","V3/107","V3/108","V3/109",
"S3/110","S3/111","S3/112","S3/113","S3/114","S3/115","S3/116","S3/117","S3/118","S3/119",
"S3/120","S3/121","S3/122","S3/123","S3/124","S3/125","S3/126","S3/127","S3/128","S3/129",
"L3/130","L3/131","L3/132","L3/133","L3/134","L3/135","L3/136","L3/137","L3/138","L3/139",
]

def forwards(apps, schema_editor):
    Battery = apps.get_model('rental', 'Battery')
    for sc in CODES:
        if sc.startswith(('V3/','L3/')):
            price = Decimal('1500.00')
        else:
            price = Decimal('1300.00')
        obj, created = Battery.objects.get_or_create(short_code=sc, defaults={
            'cost_price': price,
        })
        if not created:
            if not obj.cost_price or obj.cost_price == 0:
                obj.cost_price = price
                obj.save(update_fields=['cost_price'])

def backwards(apps, schema_editor):
    Battery = apps.get_model('rental', 'Battery')
    Battery.objects.filter(short_code__in=CODES).delete()

class Migration(migrations.Migration):
    dependencies = [
        ('rental', '0009_battery_status_historicalbattery_status'),
    ]
    operations = [
        migrations.RunPython(forwards, backwards),
    ]

