# Generated by Django 5.0.7 on 2025-09-24 22:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0012_seed_finance_partners_opening'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='idx_exp_date'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_source'], name='idx_exp_source'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['paid_by_partner'], name='idx_exp_partner'),
        ),
        migrations.AddIndex(
            model_name='moneytransfer',
            index=models.Index(fields=['date'], name='idx_mt_date'),
        ),
        migrations.AddIndex(
            model_name='moneytransfer',
            index=models.Index(fields=['purpose', 'use_collected'], name='idx_mt_purpose_usecol'),
        ),
        migrations.AddIndex(
            model_name='moneytransfer',
            index=models.Index(fields=['from_partner'], name='idx_mt_from'),
        ),
        migrations.AddIndex(
            model_name='moneytransfer',
            index=models.Index(fields=['to_partner'], name='idx_mt_to'),
        ),
        migrations.AddIndex(
            model_name='moneytransfer',
            index=models.Index(fields=['from_partner', 'purpose', 'use_collected', 'date'], name='idx_mt_from_pud'),
        ),
        migrations.AddIndex(
            model_name='moneytransfer',
            index=models.Index(fields=['to_partner', 'purpose', 'use_collected', 'date'], name='idx_mt_to_pud'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['type', 'date'], name='idx_pay_type_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_by', 'date'], name='idx_pay_user_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['date'], name='idx_pay_date'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['type'], name='idx_pay_type'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_by'], name='idx_pay_user'),
        ),
    ]
