# Generated by Django 5.0.7 on 2025-09-27 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_expense_idx_exp_date_expense_idx_exp_source_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOverviewProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Финансы',
                'verbose_name_plural': 'Финансы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rental.payment',),
        ),
        migrations.AddField(
            model_name='historicalownerwithdrawal',
            name='reclassified_contribution',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rental.ownercontribution'),
        ),
        migrations.AddField(
            model_name='historicalownerwithdrawal',
            name='reclassified_to_investment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownerwithdrawal',
            name='reclassified_contribution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_withdrawal', to='rental.ownercontribution'),
        ),
        migrations.AddField(
            model_name='ownerwithdrawal',
            name='reclassified_to_investment',
            field=models.BooleanField(default=False),
        ),
    ]
