# Generated by Django 5.0.7 on 2025-09-28 15:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0014_financeoverviewproxy_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='historicalexpense',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Расход', 'verbose_name_plural': 'historical Расходы'},
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='idx_exp_source',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='paid_source',
        ),
        migrations.RemoveField(
            model_name='historicalexpense',
            name='paid_source',
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(choices=[('purchase', 'Закупка'), ('deposit', 'Внесение денег')], default='purchase', max_length=16),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='payment_type',
            field=models.CharField(choices=[('purchase', 'Закупка'), ('deposit', 'Внесение денег')], default='purchase', max_length=16),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['payment_type'], name='idx_exp_type'),
        ),
    ]
