# Generated by Django 5.2.4 on 2026-02-11 22:13

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_add_end_reason_to_rental_battery_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOverviewProxy2',
            fields=[
            ],
            options={
                'verbose_name': 'Бухучёт',
                'verbose_name_plural': 'Бухучёт',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rental.payment',),
        ),
        migrations.AlterModelOptions(
            name='battery',
            options={'verbose_name': 'Батарея', 'verbose_name_plural': 'Батареи'},
        ),
        migrations.AlterModelOptions(
            name='batterystatuslog',
            options={'verbose_name': 'Лог статуса батареи', 'verbose_name_plural': 'Логи статусов батарей'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Категория расходов', 'verbose_name_plural': 'Категории расходов'},
        ),
        migrations.AlterModelOptions(
            name='financeadjustment',
            options={'verbose_name': 'Финансовая корректировка', 'verbose_name_plural': 'Финансовые корректировки'},
        ),
        migrations.AlterModelOptions(
            name='financepartner',
            options={'verbose_name': 'Финансовый партнёр', 'verbose_name_plural': 'Финансовые партнёры'},
        ),
        migrations.AlterModelOptions(
            name='historicalbattery',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Батарея', 'verbose_name_plural': 'historical Батареи'},
        ),
        migrations.AlterModelOptions(
            name='historicalbatterystatuslog',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Лог статуса батареи', 'verbose_name_plural': 'historical Логи статусов батарей'},
        ),
        migrations.AlterModelOptions(
            name='historicalbatterytransfer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Перенос батареи', 'verbose_name_plural': 'historical Переносы батарей'},
        ),
        migrations.AlterModelOptions(
            name='historicalclient',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Клиент', 'verbose_name_plural': 'historical Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='historicalexpensecategory',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Категория расходов', 'verbose_name_plural': 'historical Категории расходов'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinanceadjustment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Финансовая корректировка', 'verbose_name_plural': 'historical Финансовые корректировки'},
        ),
        migrations.AlterModelOptions(
            name='historicalfinancepartner',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Финансовый партнёр', 'verbose_name_plural': 'historical Финансовые партнёры'},
        ),
        migrations.AlterModelOptions(
            name='historicalmoneytransfer',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Денежный перевод', 'verbose_name_plural': 'historical Денежные переводы'},
        ),
        migrations.AlterModelOptions(
            name='historicalownercontribution',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Взнос владельца', 'verbose_name_plural': 'historical Взносы владельцев'},
        ),
        migrations.AlterModelOptions(
            name='historicalownerwithdrawal',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Вывод владельца', 'verbose_name_plural': 'historical Выводы владельцев'},
        ),
        migrations.AlterModelOptions(
            name='historicalpayment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Платеж', 'verbose_name_plural': 'historical Платежи'},
        ),
        migrations.AlterModelOptions(
            name='historicalrental',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Аренда', 'verbose_name_plural': 'historical Аренды'},
        ),
        migrations.AlterModelOptions(
            name='historicalrentalbatteryassignment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Привязка батареи', 'verbose_name_plural': 'historical Привязки батарей'},
        ),
        migrations.AlterModelOptions(
            name='historicalrepair',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Ремонт', 'verbose_name_plural': 'historical Ремонты'},
        ),
        migrations.AlterModelOptions(
            name='moneytransfer',
            options={'verbose_name': 'Денежный перевод', 'verbose_name_plural': 'Денежные переводы'},
        ),
        migrations.AlterModelOptions(
            name='ownercontribution',
            options={'verbose_name': 'Взнос владельца', 'verbose_name_plural': 'Взносы владельцев'},
        ),
        migrations.AlterModelOptions(
            name='ownerwithdrawal',
            options={'verbose_name': 'Вывод владельца', 'verbose_name_plural': 'Выводы владельцев'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Платеж', 'verbose_name_plural': 'Платежи'},
        ),
        migrations.AlterModelOptions(
            name='rental',
            options={'verbose_name': 'Аренда', 'verbose_name_plural': 'Аренды'},
        ),
        migrations.AlterModelOptions(
            name='rentalbatteryassignment',
            options={'ordering': ['start_at', 'id'], 'verbose_name': 'Привязка батареи', 'verbose_name_plural': 'Привязки батарей'},
        ),
        migrations.AlterModelOptions(
            name='repair',
            options={'verbose_name': 'Ремонт', 'verbose_name_plural': 'Ремонты'},
        ),
        migrations.RemoveIndex(
            model_name='battery',
            name='idx_battery_status',
        ),
        migrations.RemoveIndex(
            model_name='battery',
            name='idx_battery_serial',
        ),
        migrations.RemoveIndex(
            model_name='battery',
            name='idx_battery_city',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='idx_client_name',
        ),
        migrations.RemoveIndex(
            model_name='client',
            name='idx_client_city',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='idx_expense_type_date',
        ),
        migrations.RemoveIndex(
            model_name='expense',
            name='idx_expense_partner_date',
        ),
        migrations.RemoveIndex(
            model_name='moneytransfer',
            name='idx_transfer_date',
        ),
        migrations.RemoveIndex(
            model_name='moneytransfer',
            name='idx_transfer_from',
        ),
        migrations.RemoveIndex(
            model_name='moneytransfer',
            name='idx_transfer_to',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_payment_date_type',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_payment_rental_type',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_payment_date_desc',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='idx_payment_city',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='idx_rental_client_status',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='idx_rental_status_start',
        ),
        migrations.RemoveIndex(
            model_name='rental',
            name='idx_rental_city',
        ),
        migrations.RemoveIndex(
            model_name='rentalbatteryassignment',
            name='idx_rba_rental_start',
        ),
        migrations.RemoveIndex(
            model_name='rentalbatteryassignment',
            name='idx_rba_dates',
        ),
        migrations.RemoveIndex(
            model_name='rentalbatteryassignment',
            name='idx_rba_battery_start',
        ),
        migrations.RenameIndex(
            model_name='batterytransfer',
            new_name='rental_batt_status_417472_idx',
            old_name='rental_batte_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='batterytransfer',
            new_name='rental_batt_battery_65fdea_idx',
            old_name='rental_batte_battery_status_idx',
        ),
        migrations.AddField(
            model_name='expense',
            name='related_transfer',
            field=models.ForeignKey(blank=True, help_text='Перевод, по которому начислена комиссия модератору', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_expenses', to='rental.moneytransfer', verbose_name='Связанный перевод'),
        ),
        migrations.AddField(
            model_name='financepartner',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Процент комиссии модератора (например, 10.00 = 10%)', max_digits=5, verbose_name='Комиссия %'),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='related_transfer',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Перевод, по которому начислена комиссия модератору', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rental.moneytransfer', verbose_name='Связанный перевод'),
        ),
        migrations.AddField(
            model_name='historicalfinancepartner',
            name='commission_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Процент комиссии модератора (например, 10.00 = 10%)', max_digits=5, verbose_name='Комиссия %'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='payment_type',
            field=models.CharField(choices=[('purchase', 'Закупка'), ('deposit', 'Внесение личных средств')], default='purchase', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalbatterystatuslog',
            name='kind',
            field=models.CharField(choices=[('rented', 'В аренде'), ('service', 'Сервис'), ('available', 'Доступный'), ('sold', 'Продана')], max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalexpense',
            name='payment_type',
            field=models.CharField(choices=[('purchase', 'Закупка'), ('deposit', 'Внесение личных средств')], default='purchase', max_length=16),
        ),
        migrations.AlterField(
            model_name='historicalpayment',
            name='rental',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='rental.rental', verbose_name='Аренда'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='rental',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental.rental', verbose_name='Аренда'),
        ),
    ]
