# Generated by Django 5.2.4 on 2026-02-11 22:13
# Minimal migration: only commission_percent, related_transfer, and proxy state.
# Removed AlterModelOptions, RemoveIndex, RenameIndex to avoid "relation does not exist"
# on production where index names may differ.

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0025_add_end_reason_to_rental_battery_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceOverviewProxy2',
            fields=[
            ],
            options={
                'verbose_name': 'Бухучёт',
                'verbose_name_plural': 'Бухучёт',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('rental.payment',),
        ),
        migrations.AddField(
            model_name='expense',
            name='related_transfer',
            field=models.ForeignKey(
                blank=True,
                help_text='Перевод, по которому начислена комиссия модератору',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='commission_expenses',
                to='rental.moneytransfer',
                verbose_name='Связанный перевод',
            ),
        ),
        migrations.AddField(
            model_name='financepartner',
            name='commission_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Процент комиссии модератора (например, 10.00 = 10%)',
                max_digits=5,
                verbose_name='Комиссия %',
            ),
        ),
        migrations.AddField(
            model_name='historicalexpense',
            name='related_transfer',
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text='Перевод, по которому начислена комиссия модератору',
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name='+',
                to='rental.moneytransfer',
                verbose_name='Связанный перевод',
            ),
        ),
        migrations.AddField(
            model_name='historicalfinancepartner',
            name='commission_percent',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                help_text='Процент комиссии модератора (например, 10.00 = 10%)',
                max_digits=5,
                verbose_name='Комиссия %',
            ),
        ),
    ]
